### ISSUE TITLE
Dev-harness gives me a blank webpage on 8080.

### ISSUE THREAD

**Issue by ghost** [alteryx/dev-harness#13]
I've been trying to run Alteryx UI, and it wouldn't show in my designer. So, I tried running dev-harness in order to debug this but after many node module incompatibilities and chokidar resource locks I was able to run it and it gave me a blank page.
<img width="960" alt="thumbnail_image001" src="https://github.com/alteryx/dev-harness/assets/134634150/a6b617f7-2e9d-4be0-8748-9cbff7f3ef47">
<img width="960" alt="thumbnail_image002" src="https://github.com/alteryx/dev-harness/assets/134634150/15270836-13e8-4ce7-aa4f-4b4da4a206c1">
I resolved the 'resource lock' by deleting createMuitheme which would throw an error causing compiling error.

**Comment by kingedward35** [comment]
Hey Deepta, do you get any errors when you look into the console?

**Comment by ghost** [comment]
I do not get any errors in my console [for dev-harness] apart from the 24 high vulnerabilities, I don't see any other noticeable issue pop ups.

In designer, I don't get errors there as well. The only errors that pop up are usually when I don't connect the tool to a input or a output tool. Nothing about the UI pops up.

**Comment by kingedward35** [comment]
Do you know which version of node-js you are using?

**Comment by ghost** [comment]
Yes, 14.21.3

**Comment by kingedward35** [comment]
What does your setup for the dev-harness look like?

**Comment by ghost** [comment]
I'm not sure which setup you are asking for...So i'll try to cover some. I have it cloned and configured to use one of the templates as end points. I usually run `npm install --no-cache` to disregard cache.

**Comment by kingedward35** [comment]
I guess I am asking what does the file which has the UI that you want to display look like?

**Comment by ghost** [comment]
I'm using one of the in-built templates. Currently haven't included anything new, just trying to display existing UI in the index.tsx file.

**Comment by kingedward35** [comment]
Which templates are you referring to? Is a Alteryx-UI template, or a template for the Python SDK?

**Comment by ghost** [comment]
<img width="1728" alt="image" src="https://github.com/alteryx/dev-harness/assets/134634150/6f57f60e-dd24-4bd4-9776-3febcdb6f262">

Alteryx UI with react components

**Comment by kingedward35** [comment]
Can you show me your `index.html` file?

**Comment by ghost** [comment]
<img width="824" alt="image" src="https://github.com/alteryx/dev-harness/assets/134634150/8b458f0c-5cd6-4c19-9b89-c82ae05b325d">

**Comment by kingedward35** [comment]
Do you have a link to the dev-harness repo? Nevermind. I see we are in it.

**Comment by kingedward35** [comment]
So when you run `npm run start`, you don't get the following webpage? 
<img width="1792" alt="image" src="https://github.com/alteryx/dev-harness/assets/12418717/5bf3036a-76ad-4a44-b4fe-ddbed94daa1c">

**Comment by ghost** [comment]
No I get the screenshot I sent earlier.

**Comment by kingedward35** [comment]
What happens if you comment out line 11? `color: theme.palette.brand.corporateBlue`

**Comment by ghost** [comment]
I get a blank page but console gives an additional line:
`The corejs option only has an effect when the useBuiltIns option is not false`

**Comment by kingedward35** [comment]
What browser are you currently using?

**Comment by ghost** [comment]
Chrome

**Comment by kingedward35** [comment]
Can you try opening the same page in Firefox?

**Comment by ghost** [comment]
<img width="1727" alt="image" src="https://github.com/alteryx/dev-harness/assets/134634150/0246555d-d381-43a7-9c00-60e755db4d8c">

**Comment by kingedward35** [comment]
It looks like you are on the localhost port 65000. Can you change it to 8080?

**Comment by ghost** [comment]
It was initially 8080 then I was suggested it might not work if 8080 is already in use by some other app so switched it to 65000.
<img width="1728" alt="image" src="https://github.com/alteryx/dev-harness/assets/134634150/a4da1a93-84b9-4fbf-ad26-021f850a1b14">

**Comment by kingedward35** [comment]
Can you show me your console?

**Comment by ghost** [comment]
<img width="1238" alt="image" src="https://github.com/alteryx/dev-harness/assets/134634150/9e0e29e2-ae68-43a7-b799-267bea6006cc">
Most recent...

**Comment by kingedward35** [comment]
I mean the console in the browser?

**Comment by ghost** [comment]
<img width="550" alt="image" src="https://github.com/alteryx/dev-harness/assets/134634150/4779b419-6b9d-4b38-b9d0-cb0263fee385">

**Comment by kingedward35** [comment]
So it looks like the `createMuiTheme` might be the issue.

**Comment by ghost** [comment]
It might be because I deleted createMuiTheme since chokidar would say resource is locked when it was present

**Comment by kingedward35** [comment]
If you delete the current repo and clone it again and do a `npm install`, can you see if that will work for you?

**Comment by ghost** [comment]
It works!
<img width="1728" alt="image" src="https://github.com/alteryx/dev-harness/assets/134634150/716558f6-2133-4a7a-967a-056987fb5a49">

**Comment by kingedward35** [comment]
Nice.

**Comment by kingedward35** [comment]
Hope this gets you unblocked.

**Comment by ghost** [comment]
Can you please tell me why this happens? Because my UI in designer still doesn't show up so if you can tell me why this occurs I can possibly resolve it too.

**Comment by kingedward35** [comment]
If I am honest I am not sure. I think what might have happened in this case is that when you deleted the `package-lock.json` file, it might have installed newer dependencies than the ones that were in the lock file and caused some version mismatches. I think when you installed the repo fresh, it used the lock file that was in the repo and all of the dependencies were using compatible versions.

**Comment by ghost** [comment]
I'll try replicating the package-lock from dev-harness into mine. That could possibly work thanks!

**Comment by kingedward35** [comment]
No problem. If you wouldn't mind, would you update community letting them know you might be unblocked?

**Comment by ghost** [comment]
sure!
<img width="1237" alt="image" src="https://github.com/alteryx/dev-harness/assets/134634150/c1ad1687-cb1b-4447-8668-7838253b2f09">
Looks like you're right there is a mismatch. Will it work if I uninstall the entire thing and start custom tool development steps again from scratch?

**Comment by kingedward35** [comment]
I think so. Assuming you are using a compatible Node JS version in Designer, I think it should work the same. I think supported versions should be Node JS 12 and 14.
