### ISSUE TITLE
UI SDK Could not resolve dependency: typescript

### ISSUE THREAD

**Issue by cyberbit** [alteryx/dev-harness#9]
There looks to be a dependency issue with typescript when setting up the UI SDK. This error occurs when running `npm install` or using the CLI commands to package a plugin.

```npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: react-intl@5.25.1
npm ERR! Found: typescript@3.9.7
npm ERR! node_modules/typescript
npm ERR!   peerOptional typescript@"^4.5" from @formatjs/intl@2.2.1
npm ERR!   node_modules/react-intl/node_modules/@formatjs/intl
npm ERR!     @formatjs/intl@"2.2.1" from react-intl@5.25.1
npm ERR!     node_modules/react-intl
npm ERR!       react-intl@"^5.8.1" from the root project
npm ERR!       1 more (@alteryx/ui)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peerOptional typescript@"^4.5" from react-intl@5.25.1
npm ERR! node_modules/react-intl
npm ERR!   react-intl@"^5.8.1" from the root project
npm ERR!   peer react-intl@"^5.8.1" from @alteryx/ui@1.4.5
npm ERR!   node_modules/@alteryx/ui
npm ERR!     @alteryx/ui@"^1.0.0" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: typescript@4.7.4
npm ERR! node_modules/typescript
npm ERR!   peerOptional typescript@"^4.5" from react-intl@5.25.1
npm ERR!   node_modules/react-intl
npm ERR!     react-intl@"^5.8.1" from the root project
npm ERR!     peer react-intl@"^5.8.1" from @alteryx/ui@1.4.5
npm ERR!     node_modules/@alteryx/ui
npm ERR!       @alteryx/ui@"^1.0.0" from the root project```

**Comment by aParadowski** [comment]
Hey cyberbit, I am taking a look at this issue currently. Locally, I am unable to reproduce the issue you described above. Is this happening with a fresh pulldown of the `dev-harness` followed by a `npm install` at the root? If not, can you provide the steps you took to see this issue?

Another potential vector of dependency resolution issues could be the `node`/`npm` versions you have running locally. Can you run `npm -v` and `node -v` and let us know what version of each you are running?

**Comment by cyberbit** [comment]
Versions:
```
node: 16.16.0
npm: 8.11.0
```

A fresh pull and install did seem to work. I will try a new initialization from the AYX console tool as well, maybe there is something special with that configuration.

**Comment by cyberbit** [comment]
OK, I was able to reproduce with `ayx_plugin_cli`. These steps assume a conda environment and `ayx_plugin_cli` are active and installed.

1. Initialize new workspace: `ayx_plugin_cli sdk-workspace-init`.
2. Create new plugin: `ayx_plugin_cli create-ayx-plugin --tool-name TestTool`. This seems to be successful and `dev-harness` under TestTool actually runs fine at this point.
3. Create plugin package: `ayx_plugin_cli create-yxi`. This returns the error described above. `dev-harness` still runs fine though.

Apologies if this is the wrong place for plugin CLI issues.

**Comment by aParadowski** [comment]
Thanks for those steps! Running through the guide found here https://help.alteryx.com/developer-help/platform-sdk-quickstart-guide as well as the steps you took, I am still unable to recreate what you're seeing. After running `ayx_plugin_cli create-yxi` do you see the error, or does it show up when you navigate into `ui/{ToolName}` then run `npm install` in that directory? To ensure we're comparing apples to apples, these are the versions of everything I have installed:

- `node` - 12.22.6
- `npm` - 6.14.15
- `python` - 3.8.2
- `ayx_plugin_cli` - 1.0.3
- `dev-harness` - 1.0.0 (pulled down as part of the initialization)
- `Alteryx Designer` - 2022.1

After running `npm install`, I am able to render the UI with `npm run start` and things appear to be working as intended.

**Comment by cyberbit** [comment]
Ah, I think it must have been my version of node. I uninstalled it completely and reinstalled the most recent 12.x release. I ran a fresh `ayx_plugin_cli sdk-workspace-init` and everything seems to compile and package correctly now. I can't remember seeing Node 12 as a requirement for the new SDK but I may have missed it. Thank you for your help!
